### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tfausak** [guilleiguaran/fakeredis#141]
[A lot has changed since v0.5.0.](https://github.com/guilleiguaran/fakeredis/compare/v0.5.0...master)

**Comment by carsonreinke** [comment]
:+1:

**Comment by silvermind** [comment]
:+1:

**Comment by mikefischer** [comment]
:+1:

**Comment by gueyeb** [comment]
:+1:

**Comment by tubaxenor** [comment]
:+1:

**Comment by ngan** [comment]
:+1:

**Comment by guilleiguaran** [comment]
Sorry, I will release a new version asap

**Comment by tfausak** [comment]
:confused:

**Comment by KonstantinKo** [comment]
:+1: 
It's been over a year since the last update

**Comment by florrain** [comment]
:+1:

**Comment by marnen** [comment]
@guilleiguaran You promised a new release in July, but there is none 5 months later. What's the problem? Can I help?

**Comment by froderik** [comment]
Would be great with a new version!

**Comment by main24** [comment]
Double this, new version would be great.

**Comment by haraldkrischner** [comment]
For rails 5 compatibility I was forced to use the github version. So it would be a good moment for a release, wouldn't it?

**Comment by fbjork** [comment]
+1 would be great to see a version that supports `redis` 3.3

**Comment by guilleiguaran** [comment]
v0.6.0 have been pushed to rubygems
