### ISSUE TITLE
Key expiry should inclusively compare to current time

### ISSUE THREAD

**Issue by mhuggins** [guilleiguaran/fakeredis#148]
The expiration check is using a `<` rather than `<=` operator to compare timestamps.

Currently:

```ruby
expires.include?(key) && expires[key] < Time.now
```

Should be:

```ruby
expires.include?(key) && expires[key] <= Time.now
```

**Comment by guilleiguaran** [comment]
@mhuggins thanks for you bug report, let me know if you want to create a pull request fixing it or if you prefer I can fix it :smile:

**Comment by mhuggins** [comment]
I can definitely update!  Just wanted to validate & make sure I wasn't crazy first. :)
