### ISSUE TITLE
LoadError: cannot load such file -- fakeredis/minitest

### ISSUE THREAD

**Issue by cvandermeer** [guilleiguaran/fakeredis#156]
LoadError: cannot load such file -- fakeredis/minitest

Rails 4.2.4
Ruby 2.2.3

**Comment by shanys8** [comment]
I am having the same issue too.. anyone?

**Comment by caius** [comment]
I suspect this might be due to rails 4 not loading minitest out the box anymore. Perhaps try requiring `minitest/spec` before `fakeredis` in your test environment?

**Comment by shanys8** [comment]
Still won't solve it
Rails 4.1.2
Ruby 2.3.0
Any other idea?

**Comment by diegodurs** [comment]
The bundle is pretty old. The last version has been updated 2 year ago. 
If I look at my gem files, I don't have any minitest.rb.
```
root@f5fcb0290165:/app/microservices# gem which fakeredis
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fakeredis-0.5.0/lib/fakeredis.rb
root@f5fcb0290165:~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fakeredis-0.5.0/lib/fakeredis# ls -l
total 36
-rw-r--r-- 1 root root  575 Feb  2 13:46 command_executor.rb
-rw-r--r-- 1 root root 1193 Feb  2 13:46 expiring_hash.rb
-rw-r--r-- 1 root root  407 Feb  2 13:46 rspec.rb
-rw-r--r-- 1 root root 2536 Feb  2 13:46 sorted_set_argument_handler.rb
-rw-r--r-- 1 root root 2051 Feb  2 13:46 sorted_set_store.rb
-rw-r--r-- 1 root root 3344 Feb  2 13:46 sort_method.rb
-rw-r--r-- 1 root root 1657 Feb  2 13:46 transaction_commands.rb
-rw-r--r-- 1 root root   41 Feb  2 13:46 version.rb
-rw-r--r-- 1 root root  710 Feb  2 13:46 zset.rb
```

To solve it, I pointed the git in my Gemfile:
`gem "fakeredis", git: 'https://github.com/guilleiguaran/fakeredis'`
Which is not a real nice solution.

I guess this repo is down and need contributors.

**Comment by isaacsanders** [comment]
It doesn't appear that `fakeredis/minitest` is in the latest version of the gem.

**Comment by williamweckl** [comment]
Any updates on this one? Having the same problem...

**Comment by williamweckl** [comment]
Using master solved my problem...

**Comment by caius** [comment]
v0.6.0 of fakeredis was released in August 2016 and should contain the `minitest.rb` file.

Thanks for reporting this, and please reopen if your issue hasn't been solved.
