### ISSUE TITLE
New Rubygems version/release?

### ISSUE THREAD

**Issue by syndbg** [guilleiguaran/fakeredis#163]
Any chances you can push a new release in Rubygems after to the recent addition of Pubsub and  `zrangebylex` commands?

The last one is from 2014.

**Comment by carsonreinke** [comment]
See https://github.com/guilleiguaran/fakeredis/issues/141

**Comment by guilleiguaran** [comment]
#141

**Comment by syndbg** [comment]
Thanks :+1:
