### ISSUE TITLE
How should I load fake redis on Rails development environment? 

### ISSUE THREAD

**Issue by knagode** [guilleiguaran/fakeredis#173]
If I put this code into my initialization: 

```
require "fakeredis"
$redis = Redis.new
```

I get the following error: `uninitialized constant Redis`. I have fakeredis in my gemfile file in development group. 

What am I doing wrong?

**Comment by ChanChar** [comment]
@knagode you also need the [`redis-rb` gem](https://github.com/redis/redis-rb).
