### ISSUE TITLE
CommandError unknown command 'to_ary'

### ISSUE THREAD

**Issue by thedrow** [guilleiguaran/fakeredis#174]
```
Failure/Error: puts $redis

     Redis::CommandError:
       ERR unknown command 'to_ary'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/fakeredis-0.6.0/lib/fakeredis/command_executor.rb:12:in `write'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:257:in `block in write'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:236:in `io'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:255:in `write'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:214:in `block (3 levels) in process'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:208:in `each'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:208:in `block (2 levels) in process'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:353:in `ensure_connected'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/bundler/gems/db_stats-903b8106a501/lib/db_stats/connectors/redis.rb:7:in `block in <class:Client>'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:36:in `block in call_with_newrelic_trace'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/datastores.rb:111:in `wrap'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:35:in `call_with_newrelic_trace'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis.rb:2556:in `block in method_missing'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
     # /Users/omer.katz/.rvm/gems/ruby-2.2.0@fiverr_v2/gems/redis-3.2.1/lib/redis.rb:2555:in `method_missing'
     # ./spec/models/order_spec.rb:15:in `puts'
     # ./spec/models/order_spec.rb:15:in `puts'
     # ./spec/models/order_spec.rb:15:in `block (3 levels) in <top (required)>'
```

Any idea why is this happening?

**Comment by caius** [comment]
@thedrow are you still seeing this issue please?

**Comment by thedrow** [comment]
I no longer have access to the code that reproduced this issue.

**Comment by satyainmar** [comment]
I am receiving this error

**Comment by gmuscia25** [comment]
What is this


Sent from Yahoo Mail for iPhone


On Thursday, May 28, 2020, 7:58 AM, Satya Narayana Murthy Kota <notifications@github.com> wrote:




I am receiving this error

**Comment by satyainmar** [comment]
I am running rspec test locally. So, I receive the below error:

Redis::CommandError:                                                                                                  
TestRun_1   |        ERR unknown command 'to_ary'                                                                                        
TestRun_1   |      # /usr/local/bundle/gems/fakeredis-0.6.0/lib/fakeredis/command_executor.rb:12:in `write'                              
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:271:in `block in write'                                      
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:250:in `io'                                                  
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:269:in `write'                                               
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:228:in `block (3 levels) in process'                         
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in `each'                                                
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in `block (2 levels) in process'                         
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:367:in `ensure_connected'                                    
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'                                    
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'                                             
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'                                             
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'                                                
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2705:in `block in method_missing'                                   
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'                                        
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'                                                 
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2704:in `method_missing'                                            
TestRun_1   |      # ./app/workers/instagram_collector.rb:62:in `for_campaign'                                                           
TestRun_1   |      # ./spec/workers/instagram_collector_spec.rb:311:in `block (4 levels) in <top (required)>'

**Comment by gmuscia25** [comment]
Who is this and what is this


Sent from Yahoo Mail for iPhone


On Thursday, May 28, 2020, 9:55 AM, Satya Narayana Murthy Kota <notifications@github.com> wrote:




I am running rspec test locally. So, I receive the below error:

Redis::CommandError:
TestRun_1 | ERR unknown command 'to_ary'
TestRun_1 | # /usr/local/bundle/gems/fakeredis-0.6.0/lib/fakeredis/command_executor.rb:12:in write' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:271:in block in write'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:250:in io' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:269:in write'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:228:in block (3 levels) in process' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in each'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in block (2 levels) in process' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:367:in ensure_connected'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:221:in block in process' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:306:in logging'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:220:in process' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:120:in call'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2705:in block in method_missing' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in block in synchronize'
TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in synchronize' TestRun_1 | # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2704:in method_missing'
TestRun_1 | # ./app/workers/instagram_collector.rb:62:in for_campaign' TestRun_1 | # ./spec/workers/instagram_collector_spec.rb:311:in block (4 levels) in <top (required)>'
