### ISSUE TITLE
hyperloglog

### ISSUE THREAD

**Issue by jamesfzhang** [guilleiguaran/fakeredis#175]
Any plans on adding `pfadd`, `pfcount`, and `pfmerge` to this gem?

http://redis.io/commands#hyperloglog

**Comment by caius** [comment]
We'll need both a ruby-native (i.e., not a C extension) implementation of murmurhash2 and hyperloglog before we look at implementing those redis methods.

From a quick look around there's [one unlicensed murmurhash2 ruby implementation](http://toblog.bryans.org/2010/12/14/pure-ruby-version-of-murmurhash-2-0) and no native ruby hyperloglog implementation I can find. 🤔

**Comment by caius** [comment]
Although I wonder whether we could fake it without using the proper algorithms, and just keep a hash of value counts internally. Uses lots more memory sure, but lessens the work we need to do. (And if you really want the behaviour to be accurate/memory efficient, you probably need to be testing against redis itself.)
