### ISSUE TITLE
Test with redis-rb 4.0.0 RC1

### ISSUE THREAD

**Issue by djanowski** [guilleiguaran/fakeredis#177]
I just released redis-rb 4.0.0 RC1.

Can you please test against it and report back?

Thank you!

**Comment by guilleiguaran** [comment]
@djanowski sure, I'll do and post results here!!!

**Comment by djanowski** [comment]
FYI redis-rb 4.0 is out.

**Comment by kaspergrubbe** [comment]
We are blocked for upgrading `redis-rb` to version `4.0.0`, if you want me to I can give it a go for upgrading `fakeredis` to support the new release.

Do you have any checklist or guidance on how to accomplish an upgrade @djanowski ?

**Comment by guilleiguaran** [comment]
This seems to be working fine with redis-rb 4.0!!
