### ISSUE TITLE
Test run against redis-rb master is failing on Travis CI

### ISSUE THREAD

**Issue by caius** [guilleiguaran/fakeredis#194]
Looks like it's failing to resolve the dependencies, rather than failing to run against redis.rb. Possibly fixing this shows us whether #177 will have any failures too.

We should update the `redisrb-master.gemfile` so it installs on Travis CI.

**Comment by guilleiguaran** [comment]
Looks like tests are passing now

**Comment by guilleiguaran** [comment]
Tests are green across all supported platforms so I'm closing this for now
