### ISSUE TITLE
fakeredis doesn't support the "connection" method

### ISSUE THREAD

**Issue by eplusminus** [guilleiguaran/fakeredis#196]
Obviously there's no real hostname or port that can be returned by `connection`, it would have to use dummy values, but the method should be there if you really want to be able to drop this into any existing code that uses Redis. (One reason people may want to use it is logging: if you write the Redis URL to your log it might include a password, so logging `redis.connection[:host]` and `redis.connection[:port]` is safer.)

**Comment by guilleiguaran** [comment]
would you like to send a PR including this command?

**Comment by fatkodima** [comment]
On master, `fakeredis` already responds to `connection` method and returns a hash. So this should be closed?

```ruby
require "fakeredis"
redis = Redis.new
redis.connection
=> {:host=>"127.0.0.1", :port=>6379, :db=>0, :id=>"redis://127.0.0.1:6379/0", :location=>"127.0.0.1:6379"}
```
