### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by shaneog** [guilleiguaran/fakeredis#198]
Could a new version with Redis 4 support be released please?

**Comment by guilleiguaran** [comment]
Sure, as soon as we have test-suite working fine!!!

P.D: PRs welcome 😊

**Comment by shaneog** [comment]
Thanks for the quick response!

It seems all tests are passing. This [broken build](https://travis-ci.org/guilleiguaran/fakeredis/jobs/287313238) seems to be a transient issue with Travis CI, and not a problem with the test suite.
You (or someone with admin access to Travis) need to force a rebuild in Travis:
There is a button ↻ with the tooltip "Restart Build".

![e4m0e](https://user-images.githubusercontent.com/130415/31632762-df425424-b29c-11e7-9f16-6176a7f591d7.png)



> P.D: PRs welcome 😊

I'll **gladly** help if I can.

**Comment by shaneog** [comment]
\o/ Passing! https://travis-ci.org/guilleiguaran/fakeredis/builds/288745332

**Comment by shaneog** [comment]
Is there anything I can do to help this along? 👍

**Comment by ashu210890** [comment]
Any update on this? Need any help?

**Comment by shaneog** [comment]
Ping @guilleiguaran - any update?

**Comment by guilleiguaran** [comment]
Done: https://rubygems.org/gems/fakeredis/versions/0.7.0

**Comment by shaneog** [comment]
Thank you!
