### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jherdman** [guilleiguaran/fakeredis#200]
It seems like there are a few changes in master that would be nice (e.g. `FakeRedis.enabled?` would be awesome). Would it be possible to get a new release?

**Comment by morgoth** [comment]
It's a duplicate of https://github.com/guilleiguaran/fakeredis/issues/198
Anyway, new version release would be welcome :-) @guilleiguaran

**Comment by guilleiguaran** [comment]
Done: https://rubygems.org/gems/fakeredis/versions/0.7.0

**Comment by krzysiek1507** [comment]
@guilleiguaran could you please create a tag and release for 0.7.0? :)

**Comment by guilleiguaran** [comment]
Sorry, forgot to push the tag.

It's pushed now.

**Comment by krzysiek1507** [comment]
Thanks!
