### ISSUE TITLE
reset_all_databases should be called before the setup, not after

### ISSUE THREAD

**Issue by Aethelflaed** [guilleiguaran/fakeredis#205]
in:  https://github.com/guilleiguaran/fakeredis/blob/433a40f1a15f965690fcba16c2570c2b9680b1ac/lib/fakeredis/minitest.rb#L19

The setup may want to populate some initial data inside the database, it would be better to call `super` only after the `reset_all_databases` call

**Comment by guilleiguaran** [comment]
@Aethelflaed good point, do you want to send a PR fixing this?
