### ISSUE TITLE
cache being reseted between tests

### ISSUE THREAD

**Issue by LuanGB** [guilleiguaran/fakeredis#219]
I don't know if that was intentional to happen, but I'm facing the following issue (as described in the code below):

```ruby
require 'fakeredis'

describe 'test' do
  def redis
    @redis ||= Redis.new({})
  end

  before :all do
    redis.set 'teste', 'testeteste'
    puts redis.keys # => ["teste"]
  end

  it 'does something' do
    puts redis.keys # => []
  end
end
```

as showed, the "fake cache" is being cleared before the test starts.

**Comment by fatkodima** [comment]
Works as expected on master branch.
