### ISSUE TITLE
fakeredis is not compatible with redis-db 4.1.1

### ISSUE THREAD

**Issue by guilhermearaujo** [guilleiguaran/fakeredis#225]
A while ago, `redis-rb` updated the implementations of its `Boolify` methods: https://github.com/redis/redis-rb/commit/ebc8da62c817d2a130d5a55dde6eab27bee6bbb7
This change is available from version 4.1.1

`fakeredis` uses 0 and 1 for boolean replies, and this will break according to the `BoolifySet` changes, that now expect `'OK'` for `true` values and `nil` for `false`.
https://github.com/guilleiguaran/fakeredis/blob/7d55a16079637511c9c0f15cae5e0857732a1193/lib/fakeredis/command_executor.rb#L18-L24

I tried to fix it by updating these values on the line 23 of the snippet above, in hope that "`BoolifySet` will require an array of values", but it didn't work. Then I tried to edit the other lines (19 and 21), and it did the trick.

I'm not an expert about redis and it seemed pretty odd to my, that's why I'm opening an issue rather than sending a pull request. Is it really correct to change the lines 19 and 21 instead of 23? Or as a 3rd option, is the right fix to actually change all of them?

**Comment by pocke** [comment]
I found a related issue in redis/redis-rb repository. I put the link to make a reference between the issues.

https://github.com/redis/redis-rb/issues/846
