### ISSUE TITLE
fakeredis does not support all the redis connection arguments

### ISSUE THREAD

**Issue by nateyoder** [guilleiguaran/fakeredis#232]
Some unsupported arguments include socket_timeout, socket_connect_timeout, socket_keepalive, socket_keepalive_options, socket_type, retry_on_timeout, socket_read_size and health_check_interval.  While I wouldn't expect this to neccessarily be simiulated by fakeredis it would be nice to be able to use this in the `from_url` command.

Ex: `FakeRedis.from_url(redis_url, db=None, socket_connect_timeout=5, socket_timeout=30)`

**Comment by guilleiguaran** [comment]
@nateyoder I think your bug report is intended for the fakeredis Python project (https://github.com/jamesls/fakeredis/), this is the issue tracker for the Ruby project.
