### ISSUE TITLE
0.8.0 returning bool instead of changed count when 0 or 1

### ISSUE THREAD

**Issue by magicguitarist** [guilleiguaran/fakeredis#245]
Recently updated to 0.8.0 and we started seeing some spec failures.

It appears lines 18-23 were removed from `lib/fakeredis/command_executor.rb`
https://github.com/guilleiguaran/fakeredis/compare/v0.7.0...v0.8.0#diff-fdef1ab143affa7cb3400946214210edL18-L23 
![Screen Shot 2020-05-13 at 12 02 23 PM](https://user-images.githubusercontent.com/5070112/81842591-e0fed080-9511-11ea-9752-ed717ac6dbc2.png)

This is now making fakeredis return a bool value in (at least) the following situation:

Expected (tested with real redis):
```
[1] pry(main)> @redis.sadd("asdf", [1])
=> 1
[2] pry(main)> @redis.sadd("asdf", [2,3])
=> 2
[3] pry(main)> @redis.sadd("asdf", [3,4])
=> 1
[4] pry(main)> @redis.sadd("asdf", [1,2,3,4])
=> 0
```

Actual (tested in fakeredis 0.8.0):
```
[1] pry(main)> @redis.sadd("asdf", [1])
=> true
[2] pry(main)> @redis.sadd("asdf", [2,3])
=> 2
[3] pry(main)> @redis.sadd("asdf", [3,4])
=> true
[4] pry(main)> @redis.sadd("asdf", [1,2,3,4])
=> false
```

**Comment by marksiemers** [comment]
Could this be causing this issue: https://github.com/redis/redis-rb/issues/946

**Comment by magicguitarist** [comment]
@marksiemers I don't believe so, at least not in this version. I tested your example code on both fakeredis and real redis, and didn't run into that issue.

```
irb(main):001:0> require 'Redis'
=> true
irb(main):002:0> Redis.new.info["redis_version"]
=> "6.0.8"
irb(main):003:0> Redis.exists_returns_integer = true
=> true
irb(main):004:0> Redis.new.exists('hello')
=> 0
irb(main):005:0> Redis.new.exists?('hello')
=> false
irb(main):006:0> exit
```
```
irb(main):001:0> require 'fakeredis'
=> true
irb(main):002:0> Redis.new.info["redis_version"]
=> "3.3.5"
irb(main):003:0> Redis.exists_returns_integer = true
=> true
irb(main):004:0> Redis.new.exists('hello')
=> 0
irb(main):005:0> Redis.new.exists?('hello')
=> false
irb(main):006:0> exit
```

**Comment by jxdx** [comment]
Any idea when this will be merged?

**Comment by jxdx** [comment]
I'm upgrading to Rails 6.0.3.5, I'm using fakeredis 0.7.0 with both Rails 6.0.3.5 and Rails 5.2.4.6, this happens on rails 6 but not on rails 5 with the same version of the gem. 
redis on Rails 6 is 4.2.5
redis on Rails 5 is 3.3.5
