### ISSUE TITLE
How to fix the error 'to_ary' during test run?

### ISSUE THREAD

**Issue by satyainmar** [guilleiguaran/fakeredis#246]
Redis::CommandError:                                                                                                  
TestRun_1   |        ERR unknown command 'to_ary'                                                                                        
TestRun_1   |      # /usr/local/bundle/gems/fakeredis-0.6.0/lib/fakeredis/command_executor.rb:12:in `write'                              
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:271:in `block in write'                                      
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:250:in `io'                                                  
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:269:in `write'                                               
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:228:in `block (3 levels) in process'                         
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in `each'                                                
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:222:in `block (2 levels) in process'                         
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:367:in `ensure_connected'                                    
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'                                    
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'                                             
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'                                             
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'                                                
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2705:in `block in method_missing'                                   
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'                                        
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'                                                 
TestRun_1   |      # /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2704:in `method_missing'

**Comment by gmuscia25** [comment]
Why am I getting this!
