### ISSUE TITLE
_floatify doesn't handle negative numbers properly

### ISSUE THREAD

**Issue by gsdean** [guilleiguaran/fakeredis#260]
This seems breaks at least the following valid ZCOUNT command.

`ZCOUNT test (-1.2343 +inf`

I believe the regular expression:  https://github.com/guilleiguaran/fakeredis/blob/509822e07289a7f78e340b8be757fae662c0e0de/lib/fakeredis/zset.rb#L29

should be `/^\((-?\d+)/i` to accommodate the option - sign

**Comment by guilleiguaran** [comment]
Implemented the fix in https://github.com/guilleiguaran/fakeredis/commit/88c625aa552389c44e42dd02e1dfd7fde4565caf
