### ISSUE TITLE
Redis HMSET is deprecated. Prefer HSET in new code

### ISSUE THREAD

**Issue by JoaoFagundes** [guilleiguaran/fakeredis#261]
as per https://redis.io/commands/hmset, `hmset` command should now be deprecated and `hset` should allow multiple hash arguments, as this behavior is not happening in fakeredis, and my code providing a hash as a second parameter to `hget` is working in development/production code but not in my testing environment, throwing me:
```
ArgumentError: wrong number of arguments (given 7, expected 3)
from [...]/.rvm/gems/ruby-2.7.8/gems/fakeredis-0.7.0/lib/redis/connection/memory.rb:755:in `hset'
``` 

while i'm running my tests.

**Comment by NDuggan** [comment]
Hitting the same issue
