### ISSUE TITLE
Inconsistent re-connecting behavior between fakeredis and Redis in multi-process envs.

### ISSUE THREAD

**Issue by why-el** [guilleiguaran/fakeredis#266]
`fakeredis` does not reconnect in a child process, which is required by the main Redis Ruby library and the default driver does. Consider this code, which succeeds under the main library but fails when the fakeredis driver is used: 

```ruby
require 'redis' # Assumes Redis installed and started. You can run `redis-cli monitor` so see commands issued during this run.

begin
  redis = Redis.new
  redis.set("foo", "bar")

  _ = fork do
    puts "Reading redis value from child #{Process.pid}...#{redis.get('foo')}"
    puts "successful."
  end

  Process.wait
ensure
  redis.del("foo")
end

# We now test with fakeredis.
require 'fakeredis'

begin
  redis = Redis.new
  redis.set("foofromfakeredis", "bar")

  _ = fork do
    value = redis.get('foofromfakeredis')
    puts "Reading fake redis value from child #{Process.pid}..."
    puts "successful, value read is: #{value}"
  end

  Process.wait
ensure
  redis.del("foofromfakeredis")
end
```

simply run with `ruby file.rb`. This is not a theoretical issue. While `fakeredis` is mainly used for tests that run in a single process, there are famous libraries that fork, for instance `Spring` in test-mode. Under Spring, `fakeredis` will not work, but instead fails with the error that you will see in the above script, namely: 

```
redis-4.5.1/lib/redis/client.rb:411:in `ensure_connected': Tried to use a connection from a child process without reconnecting. You need to reconnect to Redis after forking or set :inherit_socket to true. (Redis::InheritedError)
```

Any other system that forks like this will fail, and it will be surprising behavior. I didn't look closely, but the fix to me seems rather simple: **when the client Redis library calls disconnect, just remember this state in `fakeredis` and force it to reconnect**. That is, instead of: 

```ruby
      def connected?
        true
      end

      def connect_unix(path, timeout)
      end

      def disconnect
      end
```

do: 

```ruby
      def connected?
        defined?(@disconnected) ? false : true
      end

      def connect_unix(path, timeout)
      end

      def disconnect
        @disconnected = true
      end
```

This will force the main library to break of its loop where it attempts to reconnect in the child process.

**Comment by guilleiguaran** [comment]
Implemented as suggested in https://github.com/guilleiguaran/fakeredis/commit/16d71210d452a997158143d87b89f9f5c4bbf8b3
