### ISSUE TITLE
How to use fakeredis with sidekiq?

### ISSUE THREAD

**Issue by zlx** [guilleiguaran/fakeredis#66]
Hi, guys

In my project, I use sidekiq for delay jobs. And In my Test, I want to use fakeredis as redis faker. 

But it does not work after I add `require 'fakeredis'` in my test_helper.rb

I debug and try to find why, and I find sidekiq will [require `redis/namespace`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L26) when I config sidekiq:

```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1, namespace: "cms_queues"}
end
Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1, namespace: "cms_queues"}
end
```

And fakeredis does not have the file: `redis/namespace` right now

**How does fakeredis process namespace case ? 
And how to use fakeredis with sidekiq?**

**Comment by topherhunt** [comment]
Thanks @caius, your walkthrough is a lifesaver. Sidekiq::Status doesn't play nice with Sidekiq's :fake testing mode, but with fakeredis and the config above I'm sending jobs to an in-memory queue in exactly the way I wanted.
